// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccgxfpkavdmujkhulvrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZ3hmcGthdmRtdWpraHVsdnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjI4NzIsImV4cCI6MjA2NzEzODg3Mn0.duCE1QFsJfO7C7QevQnNy0vWlXy8ZjjudNGpyNGiSZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});